### PR TITLE
Added acl-plugin parameters in startup.conf

### PR DESCRIPTION
**Pull request by a-olechtchouk**
Could any of you familiar with setting acl-plugin parameters / the acl plugin take a look and verify my documentation is correct? [ReadTheDocs link](https://a-olechtchoukvpp-docs.readthedocs.io/en/latest/gettingstarted/users/configuring/startup.html?#acl-plugin-parameters)

@Billy99 @jadenisco @mdr78 @dbarach 

Thanks.

### CODE REVIEW

**Comment by jadenisco** [comment]
Andrew,

 

I general I think the section looks good. I will send a seperate email to Andrew Yourtchenko, who is the ACL expert.

 

I think we need to put these parameters into 2 categories. Some are advanced and we need to document them, but the general user will not want to change them. Acl-plugin is in that category. Others like device, cpu the general user will want to change. 

 

Thanks,

 

John

**Comment by ayourtch** [comment]
Technically all of them look good (and thanks a lot for writing them up before I got to it!) though as I said in the email to John, all of them except maybe the max session count should end up in the “advanced” section. I would explicitly split them into the following:

1) session bihash-related  tweaks

Use when you need to adjust the parameters for the session bihash. 

2) acl match bihash related tweaks

Mostly should not be needed, except for when the acl configuration is exceedingly large

3) “the kitchen sink” 

 to be used with care after understanding and testing. Generally the stuff here may be used as a temporary workaround in case of a problem, or to test new/specialized functionality in a limited and controlled fashion. The defaults here may change over time with no warning.

**Comment by mdr78** [comment]
We need to come up with a better way to structure the configuration documentation – it isn’t easily accessible at the moment.

My vote is that all the sections become pages.
And that all the bullets become tables – what do other people think?

Ray K

**Comment by a-olechtchouk** [comment]
@mdr78 I agree that all plugin parameters should have their own section, since currently they are all on the same page.
However, I don't think that bullets should be in tables (except for frequently used plugins that have many parameters such as unix and dpdk, to help with their organization.)

**Pull request merged**
